name: prj
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.1
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.36
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.0.3
  - mkl=2019.1
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.0.2o
  - pandas=0.24.2
  - patsy=0.5.1
  - pcre=8.43
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=3.7.1
  - python-dateutil=2.8.0
  - qt=5.9.7
  - readline=7.0
  - scipy=1.1.0
  - setuptools=40.4.3
  - sip=4.19.8
  - sqlite=3.26.0
  - tk=8.6.8
  - tornado=6.0.2
  - wheel=0.32.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - apscheduler==3.5.3
    - beautifulsoup4==4.6.3
    - bs4==0.0.1
    - chardet==3.0.4
    - coala-utils==0.5.1
    - idna==2.7
    - lxml==4.2.5
    - pip==18.1
    - pymongo==3.7.2
    - pytz==2018.7
    - requests==2.20.0
    - scikit-learn==0.20.2
    - six==1.11.0
    - twitterscraper==0.9.3
    - tzlocal==1.5.1
    - urllib3==1.24

